### ISSUE TITLE
requirements.txt is not in the repo root

### ISSUE THREAD

**Issue by dacb** [learn2therm/PairProphet#4]
Seems like the `requirements.txt` should be in your repository root, particularly as it is used in the `Dockerfile`.

**Comment by halanzi** [comment]
Yeah, I think the `requirements.txt` is generated through Sphinx, which is why we put it in the docs directory. We can move it to the root, but I am unsure what are the implications. @loganroberts55 Thoughts?

**Comment by dacb** [comment]
I don't think the `requirements.txt` is generated by Sphinx.  Can we verify this?
